# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

latex: false
fortran: false

matrix:
  include:   
    - dist: precise
      r: 3.5
      addons:
        apt:
          packages:
          - libfreetype6-dev
    - dist: trusty
    - dist: xenial
      after_success:
        - Rscript -e 'covr::codecov()'
    - os: osx
      brew_packages:
      - freetype
    - os: osx
      osx_image: xcode7.3
      env:
        - PKG_CONFIG_PATH="/opt/X11/lib/pkgconfig"
      before_install: sed -i.bak 's/-isysroot /-I/g' $(R RHOME)/etc/Makeconf

addons:
  apt:
    packages:
    - libfontconfig1-dev
